### ISSUE TITLE
Bug with Backbone 0.9.10

### ISSUE THREAD

**Issue by Arkham** [javascript-playground/backbone-require-example#1]
Hey there,

I was studying a bit of Backbone and I found your little app: first of all, thanks for your effort, it is really helpful!

However, I was trying to rewrite all this to better understand all the inner workings and I found out a bug with the updated versione of Backbone (0.9.10): after adding an item to the cart, the filterItems actions always returns an empty list. I tried looking in deeper detail inside the code and I couldn't understand where to root of the problem is (I guess in collections/cart.js?).

Could you please take a look and help me understand what's going on? Thanks!

**Comment by jahnkajavaee** [comment]
I too face the same bug. Please help

<a href="http://javascripttrainingcourses.com/JS/BackboneJS-Training" title="Backbone.JS Training in Chennai">Backbone.JS Training in Chennai</a>
